services:
  - type: web
    name: fypbackend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fypbackend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fypbackend.settings
